//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("cdjamModel", "FK_Projects_domains", "domains", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(cdjamModel.domain), "Projects", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(cdjamModel.Project))]

// Original file name:
// Generation date: 11/11/2015 7:38:49 PM
namespace cdjamModel
{
    
    /// <summary>
    /// There are no comments for cdjamModel.datum in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="datum")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class datum : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new datum object.
        /// </summary>
        /// <param name="dataID">Initial value of DataID.</param>
        /// <param name="data">Initial value of data.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static datum Createdatum(int dataID, int data)
        {
            datum datum = new datum();
            datum.DataID = dataID;
            datum.data = data;
            return datum;
        }
        /// <summary>
        /// There are no comments for property DataID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int DataID
        {
            get
            {
                return this._DataID;
            }
            set
            {
                this.OnDataIDChanging(value);
                this.ReportPropertyChanging("DataID");
                this._DataID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DataID");
                this.OnDataIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _DataID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDataIDChanged();
        /// <summary>
        /// There are no comments for property data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int data
        {
            get
            {
                return this._data;
            }
            set
            {
                this.OndataChanging(value);
                this.ReportPropertyChanging("data");
                this._data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("data");
                this.OndataChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _data;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndataChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndataChanged();
    }
    /// <summary>
    /// There are no comments for cdjamModel.domain in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DomainID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="domain")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class domain : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new domain object.
        /// </summary>
        /// <param name="domainID">Initial value of DomainID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static domain Createdomain(int domainID)
        {
            domain domain = new domain();
            domain.DomainID = domainID;
            return domain;
        }
        /// <summary>
        /// There are no comments for property DomainID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int DomainID
        {
            get
            {
                return this._DomainID;
            }
            set
            {
                this.OnDomainIDChanging(value);
                this.ReportPropertyChanging("DomainID");
                this._DomainID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DomainID");
                this.OnDomainIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _DomainID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomainIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomainIDChanged();
        /// <summary>
        /// There are no comments for property Domain_Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Domain_Name
        {
            get
            {
                return this._Domain_Name;
            }
            set
            {
                this.OnDomain_NameChanging(value);
                this.ReportPropertyChanging("Domain_Name");
                this._Domain_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Domain_Name");
                this.OnDomain_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Domain_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomain_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomain_NameChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("cdjamModel", "FK_Projects_domains", "Projects")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Project Project
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Project> ProjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for cdjamModel.foodWaste in the schema.
    /// </summary>
    /// <KeyProperties>
    /// datapointID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="foodWaste")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class foodWaste : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new foodWaste object.
        /// </summary>
        /// <param name="datapointID">Initial value of datapointID.</param>
        /// <param name="date">Initial value of date.</param>
        /// <param name="weight">Initial value of weight.</param>
        /// <param name="percentGrains">Initial value of percentGrains.</param>
        /// <param name="percentFruit">Initial value of percentFruit.</param>
        /// <param name="percentVeg">Initial value of percentVeg.</param>
        /// <param name="percentDairy">Initial value of percentDairy.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static foodWaste CreatefoodWaste(int datapointID, global::System.DateTime date, double weight, double percentGrains, double percentFruit, double percentVeg, double percentDairy)
        {
            foodWaste foodWaste = new foodWaste();
            foodWaste.datapointID = datapointID;
            foodWaste.date = date;
            foodWaste.weight = weight;
            foodWaste.percentGrains = percentGrains;
            foodWaste.percentFruit = percentFruit;
            foodWaste.percentVeg = percentVeg;
            foodWaste.percentDairy = percentDairy;
            return foodWaste;
        }
        /// <summary>
        /// There are no comments for property datapointID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int datapointID
        {
            get
            {
                return this._datapointID;
            }
            set
            {
                this.OndatapointIDChanging(value);
                this.ReportPropertyChanging("datapointID");
                this._datapointID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("datapointID");
                this.OndatapointIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _datapointID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndatapointIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndatapointIDChanged();
        /// <summary>
        /// There are no comments for property date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this.ReportPropertyChanging("date");
                this._date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date");
                this.OndateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndateChanged();
        /// <summary>
        /// There are no comments for property weight in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                this.OnweightChanging(value);
                this.ReportPropertyChanging("weight");
                this._weight = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("weight");
                this.OnweightChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _weight;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnweightChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnweightChanged();
        /// <summary>
        /// There are no comments for property percentGrains in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double percentGrains
        {
            get
            {
                return this._percentGrains;
            }
            set
            {
                this.OnpercentGrainsChanging(value);
                this.ReportPropertyChanging("percentGrains");
                this._percentGrains = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("percentGrains");
                this.OnpercentGrainsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _percentGrains;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentGrainsChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentGrainsChanged();
        /// <summary>
        /// There are no comments for property percentFruit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double percentFruit
        {
            get
            {
                return this._percentFruit;
            }
            set
            {
                this.OnpercentFruitChanging(value);
                this.ReportPropertyChanging("percentFruit");
                this._percentFruit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("percentFruit");
                this.OnpercentFruitChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _percentFruit;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentFruitChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentFruitChanged();
        /// <summary>
        /// There are no comments for property percentVeg in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double percentVeg
        {
            get
            {
                return this._percentVeg;
            }
            set
            {
                this.OnpercentVegChanging(value);
                this.ReportPropertyChanging("percentVeg");
                this._percentVeg = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("percentVeg");
                this.OnpercentVegChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _percentVeg;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentVegChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentVegChanged();
        /// <summary>
        /// There are no comments for property percentDairy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public double percentDairy
        {
            get
            {
                return this._percentDairy;
            }
            set
            {
                this.OnpercentDairyChanging(value);
                this.ReportPropertyChanging("percentDairy");
                this._percentDairy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("percentDairy");
                this.OnpercentDairyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private double _percentDairy;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentDairyChanging(double value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnpercentDairyChanged();
    }
    /// <summary>
    /// There are no comments for cdjamModel.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProjectID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="Project")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Project : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="projectID">Initial value of ProjectID.</param>
        /// <param name="domainID">Initial value of DomainID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Project CreateProject(int projectID, int domainID)
        {
            Project project = new Project();
            project.ProjectID = projectID;
            project.DomainID = domainID;
            return project;
        }
        /// <summary>
        /// There are no comments for property ProjectID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this.ReportPropertyChanging("ProjectID");
                this._ProjectID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProjectID");
                this.OnProjectIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ProjectID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProjectIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProjectIDChanged();
        /// <summary>
        /// There are no comments for property DomainID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int DomainID
        {
            get
            {
                return this._DomainID;
            }
            set
            {
                this.OnDomainIDChanging(value);
                this.ReportPropertyChanging("DomainID");
                this._DomainID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DomainID");
                this.OnDomainIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _DomainID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomainIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDomainIDChanged();
        /// <summary>
        /// There are no comments for property Project_Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Name
        {
            get
            {
                return this._Project_Name;
            }
            set
            {
                this.OnProject_NameChanging(value);
                this.ReportPropertyChanging("Project_Name");
                this._Project_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Project_Name");
                this.OnProject_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanged();
        /// <summary>
        /// There are no comments for property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _description;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescriptionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for property Principal_Investigator in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Principal_Investigator
        {
            get
            {
                return this._Principal_Investigator;
            }
            set
            {
                this.OnPrincipal_InvestigatorChanging(value);
                this.ReportPropertyChanging("Principal_Investigator");
                this._Principal_Investigator = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Principal_Investigator");
                this.OnPrincipal_InvestigatorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Principal_Investigator;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPrincipal_InvestigatorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPrincipal_InvestigatorChanged();
        /// <summary>
        /// There are no comments for property Date_Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> Date_Created
        {
            get
            {
                return this._Date_Created;
            }
            set
            {
                this.OnDate_CreatedChanging(value);
                this.ReportPropertyChanging("Date_Created");
                this._Date_Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date_Created");
                this.OnDate_CreatedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date_Created;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDate_CreatedChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDate_CreatedChanged();
        /// <summary>
        /// There are no comments for property number_of_users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> number_of_users
        {
            get
            {
                return this._number_of_users;
            }
            set
            {
                this.Onnumber_of_usersChanging(value);
                this.ReportPropertyChanging("number_of_users");
                this._number_of_users = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("number_of_users");
                this.Onnumber_of_usersChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _number_of_users;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnumber_of_usersChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnumber_of_usersChanged();
        /// <summary>
        /// There are no comments for domain in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("cdjamModel", "FK_Projects_domains", "domains")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public domain domain
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for domain in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<domain> domainReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for cdjamEntities2 in the schema.
    /// </summary>
    public partial class cdjamEntities2 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new cdjamEntities2 object using the connection string found in the 'cdjamEntities2' section of the application configuration file.
        /// </summary>
        public cdjamEntities2() : 
                base("name=cdjamEntities2", "cdjamEntities2")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new cdjamEntities2 object.
        /// </summary>
        public cdjamEntities2(string connectionString) : 
                base(connectionString, "cdjamEntities2")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new cdjamEntities2 object.
        /// </summary>
        public cdjamEntities2(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "cdjamEntities2")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<datum> data
        {
            get
            {
                if ((this._data == null))
                {
                    this._data = base.CreateQuery<datum>("[data]");
                }
                return this._data;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<datum> _data;
        /// <summary>
        /// There are no comments for domains in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<domain> domains
        {
            get
            {
                if ((this._domains == null))
                {
                    this._domains = base.CreateQuery<domain>("[domains]");
                }
                return this._domains;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<domain> _domains;
        /// <summary>
        /// There are no comments for foodWastes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<foodWaste> foodWastes
        {
            get
            {
                if ((this._foodWastes == null))
                {
                    this._foodWastes = base.CreateQuery<foodWaste>("[foodWastes]");
                }
                return this._foodWastes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<foodWaste> _foodWastes;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Project>("[Projects]");
                }
                return this._Projects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Project> _Projects;
        /// <summary>
        /// There are no comments for data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTodata(datum datum)
        {
            base.AddObject("data", datum);
        }
        /// <summary>
        /// There are no comments for domains in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTodomains(domain domain)
        {
            base.AddObject("domains", domain);
        }
        /// <summary>
        /// There are no comments for foodWastes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTofoodWastes(foodWaste foodWaste)
        {
            base.AddObject("foodWastes", foodWaste);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    }
}
