//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("cdjamModel", "FK_Projects_domains", "domains", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(cdjamModel.domain), "Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(cdjamModel.Project), true)]

#endregion

namespace cdjamModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cdjamEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cdjamEntities2 object using the connection string found in the 'cdjamEntities2' section of the application configuration file.
        /// </summary>
        public cdjamEntities2() : base("name=cdjamEntities2", "cdjamEntities2")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cdjamEntities2 object.
        /// </summary>
        public cdjamEntities2(string connectionString) : base(connectionString, "cdjamEntities2")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cdjamEntities2 object.
        /// </summary>
        public cdjamEntities2(EntityConnection connection) : base(connection, "cdjamEntities2")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<datum> data
        {
            get
            {
                if ((_data == null))
                {
                    _data = base.CreateObjectSet<datum>("data");
                }
                return _data;
            }
        }
        private ObjectSet<datum> _data;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<domain> domains
        {
            get
            {
                if ((_domains == null))
                {
                    _domains = base.CreateObjectSet<domain>("domains");
                }
                return _domains;
            }
        }
        private ObjectSet<domain> _domains;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<foodWaste> foodWastes
        {
            get
            {
                if ((_foodWastes == null))
                {
                    _foodWastes = base.CreateObjectSet<foodWaste>("foodWastes");
                }
                return _foodWastes;
            }
        }
        private ObjectSet<foodWaste> _foodWastes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the data EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodata(datum datum)
        {
            base.AddObject("data", datum);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the domains EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodomains(domain domain)
        {
            base.AddObject("domains", domain);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the foodWastes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofoodWastes(foodWaste foodWaste)
        {
            base.AddObject("foodWastes", foodWaste);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="datum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class datum : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new datum object.
        /// </summary>
        /// <param name="dataID">Initial value of the DataID property.</param>
        /// <param name="data">Initial value of the data property.</param>
        public static datum Createdatum(global::System.Int32 dataID, global::System.Int32 data)
        {
            datum datum = new datum();
            datum.DataID = dataID;
            datum.data = data;
            return datum;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DataID
        {
            get
            {
                return _DataID;
            }
            set
            {
                if (_DataID != value)
                {
                    OnDataIDChanging(value);
                    ReportPropertyChanging("DataID");
                    _DataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DataID");
                    OnDataIDChanged();
                }
            }
        }
        private global::System.Int32 _DataID;
        partial void OnDataIDChanging(global::System.Int32 value);
        partial void OnDataIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.Int32 _data;
        partial void OndataChanging(global::System.Int32 value);
        partial void OndataChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="domain")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class domain : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new domain object.
        /// </summary>
        /// <param name="domainID">Initial value of the DomainID property.</param>
        public static domain Createdomain(global::System.Int32 domainID)
        {
            domain domain = new domain();
            domain.DomainID = domainID;
            return domain;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DomainID
        {
            get
            {
                return _DomainID;
            }
            set
            {
                if (_DomainID != value)
                {
                    OnDomainIDChanging(value);
                    ReportPropertyChanging("DomainID");
                    _DomainID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DomainID");
                    OnDomainIDChanged();
                }
            }
        }
        private global::System.Int32 _DomainID;
        partial void OnDomainIDChanging(global::System.Int32 value);
        partial void OnDomainIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Domain_Name
        {
            get
            {
                return _Domain_Name;
            }
            set
            {
                OnDomain_NameChanging(value);
                ReportPropertyChanging("Domain_Name");
                _Domain_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Domain_Name");
                OnDomain_NameChanged();
            }
        }
        private global::System.String _Domain_Name;
        partial void OnDomain_NameChanging(global::System.String value);
        partial void OnDomain_NameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cdjamModel", "FK_Projects_domains", "Projects")]
        public Project Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("cdjamModel.FK_Projects_domains", "Projects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="foodWaste")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class foodWaste : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new foodWaste object.
        /// </summary>
        /// <param name="datapointID">Initial value of the datapointID property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="weight">Initial value of the weight property.</param>
        /// <param name="percentGrains">Initial value of the percentGrains property.</param>
        /// <param name="percentFruit">Initial value of the percentFruit property.</param>
        /// <param name="percentVeg">Initial value of the percentVeg property.</param>
        /// <param name="percentDairy">Initial value of the percentDairy property.</param>
        public static foodWaste CreatefoodWaste(global::System.Int32 datapointID, global::System.DateTime date, global::System.Double weight, global::System.Double percentGrains, global::System.Double percentFruit, global::System.Double percentVeg, global::System.Double percentDairy)
        {
            foodWaste foodWaste = new foodWaste();
            foodWaste.datapointID = datapointID;
            foodWaste.date = date;
            foodWaste.weight = weight;
            foodWaste.percentGrains = percentGrains;
            foodWaste.percentFruit = percentFruit;
            foodWaste.percentVeg = percentVeg;
            foodWaste.percentDairy = percentDairy;
            return foodWaste;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 datapointID
        {
            get
            {
                return _datapointID;
            }
            set
            {
                if (_datapointID != value)
                {
                    OndatapointIDChanging(value);
                    ReportPropertyChanging("datapointID");
                    _datapointID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("datapointID");
                    OndatapointIDChanged();
                }
            }
        }
        private global::System.Int32 _datapointID;
        partial void OndatapointIDChanging(global::System.Int32 value);
        partial void OndatapointIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private global::System.Double _weight;
        partial void OnweightChanging(global::System.Double value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double percentGrains
        {
            get
            {
                return _percentGrains;
            }
            set
            {
                OnpercentGrainsChanging(value);
                ReportPropertyChanging("percentGrains");
                _percentGrains = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percentGrains");
                OnpercentGrainsChanged();
            }
        }
        private global::System.Double _percentGrains;
        partial void OnpercentGrainsChanging(global::System.Double value);
        partial void OnpercentGrainsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double percentFruit
        {
            get
            {
                return _percentFruit;
            }
            set
            {
                OnpercentFruitChanging(value);
                ReportPropertyChanging("percentFruit");
                _percentFruit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percentFruit");
                OnpercentFruitChanged();
            }
        }
        private global::System.Double _percentFruit;
        partial void OnpercentFruitChanging(global::System.Double value);
        partial void OnpercentFruitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double percentVeg
        {
            get
            {
                return _percentVeg;
            }
            set
            {
                OnpercentVegChanging(value);
                ReportPropertyChanging("percentVeg");
                _percentVeg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percentVeg");
                OnpercentVegChanged();
            }
        }
        private global::System.Double _percentVeg;
        partial void OnpercentVegChanging(global::System.Double value);
        partial void OnpercentVegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double percentDairy
        {
            get
            {
                return _percentDairy;
            }
            set
            {
                OnpercentDairyChanging(value);
                ReportPropertyChanging("percentDairy");
                _percentDairy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("percentDairy");
                OnpercentDairyChanged();
            }
        }
        private global::System.Double _percentDairy;
        partial void OnpercentDairyChanging(global::System.Double value);
        partial void OnpercentDairyChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cdjamModel", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="projectID">Initial value of the ProjectID property.</param>
        /// <param name="domainID">Initial value of the DomainID property.</param>
        public static Project CreateProject(global::System.Int32 projectID, global::System.Int32 domainID)
        {
            Project project = new Project();
            project.ProjectID = projectID;
            project.DomainID = domainID;
            return project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Int32 _ProjectID;
        partial void OnProjectIDChanging(global::System.Int32 value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DomainID
        {
            get
            {
                return _DomainID;
            }
            set
            {
                OnDomainIDChanging(value);
                ReportPropertyChanging("DomainID");
                _DomainID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DomainID");
                OnDomainIDChanged();
            }
        }
        private global::System.Int32 _DomainID;
        partial void OnDomainIDChanging(global::System.Int32 value);
        partial void OnDomainIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Project_Name
        {
            get
            {
                return _Project_Name;
            }
            set
            {
                OnProject_NameChanging(value);
                ReportPropertyChanging("Project_Name");
                _Project_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Project_Name");
                OnProject_NameChanged();
            }
        }
        private global::System.String _Project_Name;
        partial void OnProject_NameChanging(global::System.String value);
        partial void OnProject_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Principal_Investigator
        {
            get
            {
                return _Principal_Investigator;
            }
            set
            {
                OnPrincipal_InvestigatorChanging(value);
                ReportPropertyChanging("Principal_Investigator");
                _Principal_Investigator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Principal_Investigator");
                OnPrincipal_InvestigatorChanged();
            }
        }
        private global::System.String _Principal_Investigator;
        partial void OnPrincipal_InvestigatorChanging(global::System.String value);
        partial void OnPrincipal_InvestigatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Created
        {
            get
            {
                return _Date_Created;
            }
            set
            {
                OnDate_CreatedChanging(value);
                ReportPropertyChanging("Date_Created");
                _Date_Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Created");
                OnDate_CreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Created;
        partial void OnDate_CreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_CreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> number_of_users
        {
            get
            {
                return _number_of_users;
            }
            set
            {
                Onnumber_of_usersChanging(value);
                ReportPropertyChanging("number_of_users");
                _number_of_users = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number_of_users");
                Onnumber_of_usersChanged();
            }
        }
        private Nullable<global::System.Int32> _number_of_users;
        partial void Onnumber_of_usersChanging(Nullable<global::System.Int32> value);
        partial void Onnumber_of_usersChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("cdjamModel", "FK_Projects_domains", "domains")]
        public domain domain
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<domain> domainReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<domain>("cdjamModel.FK_Projects_domains", "domains", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
